apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: scheduler
spec:
  selector:
    app: scheduler-service
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 9000